Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.OAuth;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Reflection.Metadata.Ecma335;
using System.Security.Claims;
using webFerum.Models;
using webFerum.Models.AppContext;
using webFerum.Service;
using webFerum.Utils;




namespace webFerum.Controllers
{
    public class AuthController : Controller
    {
        private UserService userService;

        public AuthController(UserService userService) 
        {
            this.userService = userService; 
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IResult> Login([FromBody] AuthUser data)
        {
            if (data.isValid)
            {
                data.Password = Utils.Encrypt.sha256(data.Password);

                User? user = await userService.GetEmployeeAsync(new UserModel(){
                                                                    Email = data.Email, 
                                                                    Password = data.Password});

                if (user is null) Results.StatusCode(StatusCodes.Status400BadRequest);

                List<Claim> claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, data.Email),
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim("RolePolicy", user.Role.Policy)
                };

                JwtSecurityToken jwt = new JwtSecurityToken(
                        issuer: AuthOptions.ISSUER,
                        audience: AuthOptions.AUDIENCE,
                        claims: claims,
                        expires: DateTime.UtcNow.Add(TimeSpan.FromMinutes(2)),
                        signingCredentials: new SigningCredentials(AuthOptions.GetSymmetricSecurityKey(), SecurityAlgorithms.HmacSha256));

                var response = new
                {
                    accessToken = new JwtSecurityTokenHandler().WriteToken(jwt)
                };

                HttpContext.Session.SetString("accessToken", response.accessToken);

                return Results.Json(response);
            }

            return Results.StatusCode(StatusCodes.Status400BadRequest);
        }
        
    }
}

Controllers/RegistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webFerum.Models;
using webFerum.Models.AppContext;
using webFerum.Service;
using webFerum.Utils;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Web;
using System.Security.Claims;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Pomelo.EntityFrameworkCore.MySql.Query.ExpressionTranslators.Internal;

namespace webFerum.Controllers
{
    public class RegistController : Controller
    {
        private UserService userService;

        public RegistController(UserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "Admin")]
        public async Task<IResult> Add([FromBody] UserModel data)
        {
            data.Password = Encrypt.sha256(data.Password);
            int id = await userService.AddUserAsync(data);

            return Results.Json(new { Id = id });
        }

        [HttpPost]
        public async Task<IResult> Reg([FromBody] UserModel data)
        {
            data.Password = Encrypt.sha256(data.Password);
            await userService.AddUserAsync(data);

            return Results.Ok();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using webFerum.Models.AppContext
@using webFerum.Service

@inject IAuthorizationService AuthorizationService
@inject UserService userService

<!DOCTYPE html>
<html lang="en">
<head>  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webFerum</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webFerum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webFerum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Статьи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Товары и услуги</a>
                        </li>
                        @if (!@Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Авторизация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Regist" asp-action="Index">Регистрация</a>
                            </li>
                        }
                        else
                        {
                            var res = await AuthorizationService.AuthorizeAsync(User, "Admin");
                            if (res.Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="All">Пользователи</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark"  href="/logout">Выйти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - webFerum 
        </div>
    </footer
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.5.2/dist/umd/popper.min.js" integrity="sha384-XoNAYTr6J+ZevIbhzSMg1lDmqGoFwQUpvC23j9dAlw/40se/EMIIKpSGDf0Ckiiw" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>